### ISSUE TITLE
Gradle 5.6/6.x compatibility: License task not accessing project in a safe manner

### ISSUE THREAD

**Issue by shevek** [hierynomus/license-gradle-plugin#178]
Triggered by update from Gradle 4.10.3 to Gradle 5.6.

```
The configuration :<project>:runtime was resolved without accessing the project in a safe manner.  This may happen when a configuration is resolved from a thread not managed by Gradle or from a different project.  See https://docs.gradle.org/5.6/userguide/troubleshooting_dependency_resolution.html#sub:configuration_resolution_constraints for more details. This behaviour has been deprecated and is scheduled to be removed in Gradle 6.0.
        at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration.resolveToStateOrLater(DefaultConfiguration.java:566)
        at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration.getResolvedConfiguration(DefaultConfiguration.java:556)
        at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration_Decorated.getResolvedConfiguration(Unknown Source)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at groovy.lang.MetaBeanProperty.getProperty(MetaBeanProperty.java:59)
        at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration_Decorated.getProperty(Unknown Source)
        at nl.javadude.gradle.plugins.license.LicenseResolver.resolveProjectDependencies(LicenseResolver.groovy:147)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:326)
        at nl.javadude.gradle.plugins.license.LicenseResolver$_resolveProjectDependencies_closure5.doCall(LicenseResolver.groovy:155)
```

**Comment by shevek** [comment]
I think this may be causing a concurrency heisenbug where if we build iwth `--parallel` and `downloadLicenses` happens to run before `test`, we get an invalid classpath and the test fails to run.
