### ISSUE TITLE
Combining License Plugin with new Gradle Plugin Publishing Plugin fails

### ISSUE THREAD

**Issue by ysb33r** [hierynomus/license-gradle-plugin#67]
If both `nl.javadude.gradle.plugins:license-gradle-plugin:0.11.0` and `com.gradle.publish:plugin-publish-plugin:0.9.0` is on the classpath, neither `com.github.hierynomus.license` nor `com.gradle.plugin-publish` can be applied. A typical stacktrace is as follows:

```
Caused by: java.lang.NoSuchMethodError: com.google.common.collect.ImmutableList.of(Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;)Lcom/google/common/collect/ImmutableList;
	at com.gradle.publish.PublishTask.<clinit>(PublishTask.java:47)
	at org.gradle.api.internal.DependencyInjectingInstantiator.newInstance(DependencyInjectingInstantiator.java:48)
	at org.gradle.api.internal.ClassGeneratorBackedInstantiator.newInstance(ClassGeneratorBackedInstantiator.java:36)
	at org.gradle.api.internal.project.taskfactory.TaskFactory$1.call(TaskFactory.java:124)
	... 57 more
```

**Comment by ysb33r** [comment]
Just want to say that there is a workaround for this issue. As pointed out to me by @melix the problem is a guava version mismatch (Gradle uses guava-jdk5 vs this plugin which uses plain guava). Therefore by doing the following the issue is averted.

```groovy
buildscript {
    dependencies {
        classpath 'nl.javadude.gradle.plugins:license-gradle-plugin:0.11.0', {
            exclude module : 'guava'
        }
    }
}
```

**Comment by hierynomus** [comment]
@ysb33r Could you check whether this still is a problem. The new 0.12.0 release has no dependencies on guava anymore.

**Comment by ysb33r** [comment]
:+1: 

Just upgraded two projects and they both passed.

**Comment by hierynomus** [comment]
Thx!
